### ISSUE TITLE
文件命名方面的建议

### ISSUE THREAD

**Issue by AutumnLight** [giantray/stackoverflow-java-top-qa#35]
建议所有的文件命名保持一致，目前存在首字母大小写不一致的问题。

**Comment by giantray** [comment]
文档的文件名，和stackoverflowhich-notnull-java-annotation-should-i-usew上的url保持一致。例如，http://stackoverflow.com/questions/8710619/java-operator 的文件名， 就是java-operator.md

上面这个约定，在reame.md上有写。但现在的确存在不一致的情况。需要改进

**Comment by AutumnLight** [comment]
嗯，要不我一块做了，一律使用小写，然后发一个pull request 怎么样？

**Comment by giantray** [comment]
好的。请按上面说的约定搞，和stackoverflow的url保持一致，主要readme.md也要更新

**Comment by AutumnLight** [comment]
OK
