### ISSUE TITLE
是否可以引用翻译的答案

### ISSUE THREAD

**Issue by ruanyl** [giantray/stackoverflow-java-top-qa#37]
你好，我开发了一个stackoverflow的chrome extension（MIT License） [stacktransflow](https://github.com/ruanyl/stacktransflow)，功能是能让使用者在stackoverflow的页面上切换中英文翻译。

目前从该repo引用了一个翻译[stacktransflow-data](https://github.com/ruanyl/stacktransflow-data)，但是因为没有找到repo的license，在继续添加之前来征求你们的同意:) 这个chrome extension是MIT License的。

**Comment by giantray** [comment]
可以。但我觉得我们这里问题有限。命中率应该很低比。。

**Comment by ruanyl** [comment]
谢谢，初衷是希望有更多人参与 ;)
