### ISSUE TITLE
添加翻译

### ISSUE THREAD

**Issue by AutumnLight** [giantray/stackoverflow-java-top-qa#38]
希望翻译[Why is printing “B” dramatically slower than printing “#”?](http://stackoverflow.com/questions/21947452/why-is-printing-b-dramatically-slower-than-printing)
时间一周左右。

**Comment by giantray** [comment]
貌似后来没看到你翻译的版本。。不过我看了下，这个问题也有人翻译了。之前你提交过不少commit，欢迎继续参与

**Comment by AutumnLight** [comment]
嗯，好久没有坚持了。

2016-08-03 0:46 GMT+08:00 李泽扬 <notifications@github.com>:
