### ISSUE TITLE
「遍历集合时移除元素，怎样避免ConcurrentModificationException异常抛出」的链接错了！

### ISSUE THREAD

**Issue by liukai0219** [giantray/stackoverflow-java-top-qa#97]
「遍历集合时移除元素，怎样避免ConcurrentModificationException异常抛出」的链接错了！
应该是https://github.com/giantray/stackoverflow-java-top-qa/blob/master/contents/iterating-through-a-collection-avoiding-concurrentmodificationexception-when-re.md
而不是
https://github.com/giantray/stackoverflow-java-top-qa/blob/master/contents/iterating-through-a-collection-avoiding-concurrentmodificationexception-when-reiterating-through-a-collection-avoiding-concurrentmodificationexception-when-re.md

**Comment by kezhenxu94** [comment]
@liukai0219 这个项目目前貌似停止维护了
